{{- if eq .Values.workload  "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-metrics-collector.fullname" . }}
  labels:
    {{- include "k8s-metrics-collector.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "k8s-metrics-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "k8s-metrics-collector.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-metrics-collector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORKLOAD
              value: {{ .Values.workload }}
            - name: APP_VERSION
              value:  {{ .Values.image.tag | default .Chart.AppVersion }}
            {{- range $name, $value := .Values.environment }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if and (not .Values.environmentExternalSecrets.enabled) (not (eq .Values.environmentVars.type  "secret")) }}
            {{- range $name, $value := .Values.environmentSecrets }}
            {{- if not (empty $value) }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- if or (eq .Values.environmentVars.type  "secret") (.Values.environmentExternalSecrets.enabled) }}
          envFrom:
          {{- if .Values.environmentExternalSecrets.enabled }}
            - secretRef:
                name: {{ .Values.environmentExternalSecrets.name }}
          {{- else if (eq .Values.environmentVars.type  "secret") }}
            - secretRef:
                name: {{ include "k8s-metrics-collector.fullname" . }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.configmap.enabled }}
            {{- if .Values.configmap.files }}
            {{- range .Values.configmap.files }}
            - mountPath: {{ .mountPath }}
              name: files
              {{- range $name, $value := .data }}
              subPath: ..data/{{ $name }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.configmap.binaryFiles }}
            {{- range .Values.configmap.binaryFiles }}
            - mountPath: {{ .mountPath }}
              name: files
              {{- range $name, $value := .data }}
              subPath: ..data/{{ $name }}
              {{- end }}
            {{- end }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- if .Values.configmap.enabled  }}
      {{- if or .Values.configmap.files .Values.configmap.binaryFiles }}
        - name: files
          configMap:
            name: {{ include "k8s-metrics-collector.fullname" . }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
