{{- if eq .Values.environmentVars.type  "secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8s-metrics-collector.fullname" . }}
  labels:
    {{- include "k8s-metrics-collector.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.environment }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
