apiVersion: v2
appVersion: 0.3.22
description: A Helm chart for Kubernetes
name: k8s-metrics-collector
type: application
version: 0.1.25
dependencies:
- condition: kubePrometheusStack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 72.5.*
