apiVersion: v2
appVersion: 0.3.17-gcp
description: A Helm chart for Kubernetes
name: k8s-metrics-collector
type: application
version: 0.1.18
dependencies:
- condition: kubePrometheusStack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 61.9.*
