name: Helm Chart test
run-name: helm chart test 🚀
on: [push]
jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Manifests validation
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: '/kubeconform'
          args: "-summary -output json kubeconfigs/"

  test_in_k8s:
    needs: [kubeconform]
    strategy:
      matrix:
        k8s: [ 1.23, 1.24, 1.25 ]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install MicroK8s
        run: | 
          sudo snap install microk8s --classic --channel=${{ matrix.k8s }}
          sudo microk8s status --wait-ready

      - name: Test cw-agent chart
        run: |
          sudo microk8s helm3 upgrade -i cw-agent --atomic helm-chart-sources/anodot-cost-k8s-cw-agent
          sudo microk8s helm3 status cw-agent