name: Helm Chart test
run-name: helm chart test 🚀
on: [push]
jobs:
  test-on-k8s-1_25:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - run: sudo snap install microk8s --classic --channel=1.25