name: Helm Chart test
run-name: helm chart test 🚀
on: [push]
jobs:
  test-on-k8s-1_25:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install MicroK8s
        run: | 
          sudo snap install microk8s --classic --channel=1.25
          sudo microk8s status --wait-ready

      - name: Test cw-agent chart
        run: |
          sudo microk8s helm3 upgrade -i cw-agent --atomic helm-chart-sources/anodot-cost-k8s-cw-agent
          sudo microk8s helm3 status cw-agent