name: Helm Chart test
run-name: helm chart test 🚀
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Helm lint
        run: helm lint --with-subcharts helm-chart-sources/anodot-cost-k8s-cw-agent

  test_in_k8s:
    needs: [lint]
    strategy:
      matrix:
        k8s: [ 1.21, 1.23, 1.24, 1.25 ]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install MicroK8s
        run: | 
          sudo snap install microk8s --classic --channel=${{ matrix.k8s }}
          sudo microk8s status --wait-ready
          sudo microk8s enable helm3

      - name: permissions
        run: chmod +x test-chart.sh

      - name: Test anodot-cost-k8s-cw-agent chart
        run: ./test-chart.sh anodot-cost-k8s-cw-agent

      # Needed to test PrometheusRule
      - name: Install kube-prometheus-stack
        run: |
          sudo microk8s helm3 repo add prometheus-community https://prometheus-community.github.io/helm-charts
          sudo microk8s helm3 repo update
          sudo microk8s helm3 install --set grafana.enabled=false --set alertmanager.enabled=false kube-prometheus-stack prometheus-community/kube-prometheus-stack

      - name: Test k8s-metrics-collector chart
        run: ./test-chart.sh k8s-metric-collector