name: Helm Chart test
run-name: helm chart test 🚀
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Helm lint
        run: helm lint --with-subcharts helm-chart-sources/anodot-cost-k8s-cw-agent

  test_in_k8s:
    needs: [lint]
    strategy:
      matrix:
        k8s: [ 1.23, 1.24, 1.25 ]
        chart: [ anodot-cost-k8s-cw-agent, k8s-metrics-collector ]

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install MicroK8s
        run: | 
          sudo snap install microk8s --classic --channel=${{ matrix.k8s }}
          sudo microk8s status --wait-ready
          sudo microk8s enable helm3

      - name: Test chart
        run: chmod +x test-chart.sh && ./test-chart.sh ${{ chart }}